Fix cfs preparser
yamcs/yamcs pull request #561
Opened 2021-05-10 00:46 UTC by mbenson1

2021-05-10 07:06 UTC, xpromache requested changes
Can you please add an unit test for these in the ByteArrayUtilsTest. It doesn't look to me that they work correctly because
a[offset] & 0xFF <<24
will produce a negative integer if the first bit of a[offset] is 1.

I think you can use &0xFFL instead to work with 64 bit longs.

2021-05-10 07:10 UTC, xpromache reviewed
I don't see the difference between CFE_SB_TIME_32_32_SUBS and CFE_SB_TIME_32_32_M_20. Am I missing something?

2021-05-10 07:30 UTC, mbenson1 commented
Will do.  Thanks.

Sent from my iPhone

> On May 10, 2021, at 02:11, Nicolae Mihalache ***@***.***> wrote:
> 
> ﻿
> @xpromache commented on this pull request.
> 
> I don't see the difference between CFE_SB_TIME_32_32_SUBS and CFE_SB_TIME_32_32_M_20. Am I missing something?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-13 18:41 UTC, xpromache commented
thanks for the fix of the unsigned and the unit test.

I think the CFE_SB_TIME_32_32_M_20 is still broken.

2021-05-13 18:44 UTC, lorenzo-gomez-windhover commented
> thanks for the fix of the unsigned and the unit test.
> 
> I think the CFE_SB_TIME_32_32_M_20 is still broken.

Just fixed it :)

2021-05-13 18:46 UTC, lorenzo-gomez-windhover commented
Turns out CFE_SB_TIME_32_32_M_20 has 12 bits reserved as per cfs docs:
```
#define CFE_SB_TIME_32_16_SUBS   1
  32 bits seconds + 16 bits subseconds (units = 2^^-16)
#define  CFE_SB_TIME_32_32_SUBS   2
   32 bits seconds + 32 bits subseconds (units = 2^^-32)
#define  CFE_SB_TIME_32_32_M_20   3
   32 bits seconds + 20 bits microsecs + 12 bits reserved
```

2021-05-13 18:49 UTC, lorenzo-gomez-windhover commented
Quick note(unrelated to this PR):

Every time I build yamcs I have to comment out the following lines in the root `pom.xml`:

```
<!--               <additionalOption>-Xdoclint:none</additionalOption> -->
<!--               <additionalOption>-Xdoclint:html</additionalOption> -->
<!--               <additionalOption>-Xdoclint:reference</additionalOption> -->
```

It looks like there are some comments in the code base that do not comply with maven javadoc plugin. Are you guys aware of this by chance?

2021-05-13 18:49 UTC, xpromache commented
The Yamcs time is in milliseconds so the function that converts to microseconds is not right.
Plus can you make them java like (use variable starting with lowercase, camel case in function names)

2021-05-14 07:55 UTC, fqqb commented
> It looks like there are some comments in the code base that do not comply with maven javadoc plugin. Are you guys aware of this by chance?

No. If you think there's a problem there, please open a separate issue, providing output of `mvn -version` as well as the error.

2023-04-17 22:14 UTC, xpromache commented
Is this still relevant? I cannot find the corresponding code in the latest cFS release:
https://github.com/nasa/cFE/blob/main/modules/time/fsw/src/cfe_time_api.c

2026-07-23 20:08 UTC, closed without merging